### ISSUE TITLE
导入编译报错

### ISSUE THREAD

**Issue by zhao-mingjian** [JavaNoober/FloatMenu#1]
报错关键信息：Integer types not allowed (at 'duration' with value '200').

网上查了一下，好像说
    `<dimen name="duration">200</dimen>`
改成这样？
    `<integer name="duration">200</integer>`

**Comment by JavaNoober** [comment]
gradle是什么版本的

**Comment by JavaNoober** [comment]
具体调用代码，和报错信息给我看看呢

**Comment by JavaNoober** [comment]
更新1.0.3吧，可能是你调用了values.xml里duration这个字段，但是这个属性其实我在项目里没有使用到，现在我直接删掉了

**Comment by zhao-mingjian** [comment]
额，好的，谢谢！
