### ISSUE TITLE
不支持设置单个item隐藏或者显示

### ISSUE THREAD

**Issue by jin123d** [JavaNoober/FloatMenu#3]
在项目中往往需要隐藏或者显示某个item，并且点击事件中只支持position，因为item size不一致的情况中position没有id好控制。

**Comment by JavaNoober** [comment]
这里是不需要id的，position就代表了菜单从第一个到最后一个的位置，菜单是一个linearlayout。
关于某一个item的隐藏不知道你是否能通过修改传入数据源的方式去修改？

**Comment by jin123d** [comment]
@JavaNoober  我明白你的意思，可以通过修改数据源的方法来修改。但是比如现在菜单有很多item，数据源不同的话再通过position，判断逻辑就稍显复杂了，如果支持id的话就不存在这个问题了。

**Comment by JavaNoober** [comment]
更新一下1.0.4，传入的list的item类型继承MenuItem就行，再在点击事件中获取item就可以了
