### ISSUE TITLE
添加不了list<String>类型的数据

### ISSUE THREAD

**Issue by SoulofYang** [JavaNoober/FloatMenu#5]
我把演示的代码拉进项目中也会报错，不能通过list<String>进行数据的动态加载。

**Comment by JavaNoober** [comment]
请问一下你报错的log是什么

**Comment by SoulofYang** [comment]
就是找不到可以添加list<String>的方法。

**Comment by JavaNoober** [comment]
floatMenu.items(list)不行吗

**Comment by SoulofYang** [comment]
list可以，但是不能直接用字符串的list

**Comment by JavaNoober** [comment]
不是很明白你的问题，要不你加我一下qq详细讨论一下吧，818217883

**Comment by SoulofYang** [comment]
就是不能直接添加List《String》,要用List《MenuItem》

**Comment by JavaNoober** [comment]
是的，因为之前有人提需求，一个string并不难满足实际使用。所以增加了一个MenuItem，类型是其子类即可，其中包含了String，你可以使用这个，效果一样的

**Comment by SoulofYang** [comment]
建议github的说明上修改一下，可能产生误导

**Comment by JavaNoober** [comment]
好的好的，string是最早版本的了。忘记修改一下了👌
